### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/ajax-project#2]
**Objective:** Users will be able to create a profile with a name, email, username, bio and favorite team. 

**Task List:**

- [x] Compile home page html
- [x] Add CSS to style the home page
- [x] Compile login page html
- [x] Add CSS to style the login page
- [x] Compile sign up page html
- [x] Add CSS to style the sign up page
- [x] Compile my profile page html
- [x]  Add CSS to styling the my profile page
- [x] Listen for click events on the home page button's
- [x] Listen for submit events on the login and sign up page 
- [x] Create a view swapping function to switch between pages
- [x] Save sign up data to local storage
- [x] Append sign up data to the my profile page 
- [x] Test functionality
- [x] Fix bugs 
- [x] Remove CSS that had no affect
