### ISSUE TITLE
Users can create a ranking

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/ajax-project#3]
**Objective:** Users can create a custom list of NBA players, whether it be a ranking or prediction. This will feature a list title, the list itself, and an optional description. 

**Task List:**

- [x] Compile HTML for the home page
- [x] Add CSS styling to the home page 
- [x] Compile HTML for the create new ranking page 
- [x] Add css styling to the create ranking page 
- [x] Listen for click events on the home page 
- [x] Listen for click events on the create new ranking page 
- [x] Add both the home page and create new ranking page to the view swapping function 
- [x] GET NBA player data on the create ranking page via the search bar input
- [x] Listen for click events within the search bar 
- [x] Append selected NBA player data to the create ranking html page 
- [x] Ensure that when a user leaves the create ranking page without saving the data is dumped 
- [x] Test functionality 
- [x] Fix bugs 
- [x] Remove CSS with no affect
