### ISSUE TITLE
Users can save a list to their profile

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/ajax-project#4]
**Objective:** Upon creating a new list users can save that list to their profile which will show up under a “my rankings” tab.

**Task List:**

- [x] Compile HTML for the my rankings page
- [x] Add CSS styling to the my rankings page 
- [x] Listen for submit events on the "submit" button within the create a ranking page 
- [x] Save the created list within local storage 
- [x] Clear the my rankings page after a list is submitted/saved 
- [x] Append the list title of saved lists to the HTML within the my rankings page 
- [x] Listen for click events on the my rankings button within the my profile page 
- [x] Add the my rankings page to the viewswap function
- [x] Test functionality 
- [x] Fix Bugs 
- [x] Remove CSS with no affect
