### ISSUE TITLE
Users can view player stats

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/ajax-project#5]
**Objective:** Provide the option to view player stats within the "Browse Stats" page

**Task List:**

- [x] Create HTML for the browse stats page 
- [x] Add CSS styling to the browse stats page 
- [x] Listen for click events on the browse stats button
- [x] Listen for submit events on the player search form in the browse stats page 
- [x] Send an html request when player stats are searched for that returns player stats 
- [x] Append player stats to the browse stats html page 
- [x] Make sure the page is empties out when a new request is made 
- [x] Test functionality 
- [x] Fix Bugs 
- [x] Remove CSS with no affect
