### ISSUE TITLE
User can rank NBA teams

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/ajax-project#6]
**Objective:** Users can rank NBA teams 

**Task List:**

- [x] Add an option to the create a ranking page to search for NBA teams 
- [x] Listen for click events on the new search button within the create ranking page 
- [x] Append search results to the search results page 
- [x] Listen for click events on the search results page 
- [x] Append NBA team search results on the create ranking page.
- [x] Ensure that when a new list of teams is submitted it's saved to the my rankings page 
- [x] Test functionality
- [x] Fix bugs 
- [x] Remove CSS with no affect
